// Central UI vocabulary. Keep product copy here so QML layout stays readable.
pragma Singleton
import QtQuick

QtObject {
    property string language: "ru"
    readonly property var _dict: ({
        ru: {
            "app.title": "Parallel Finder", "app.stage": "локальный анализ движения", "common.seconds": "с", "common.empty": "—", "splash.loading": "Подготавливаем рабочее пространство…",
            "top.workspace": "рабочее пространство", "top.analyzing": "Анализируем", "top.ready": "Готово к работе", "top.settings": "Открыть настройки",
            "dialog.chooseVideos": "Выберите видеофайлы", "dialog.chooseFolder": "Выберите папку с видео", "dialog.videoFilter": "Видео (*.mp4 *.mov *.mkv *.avi *.webm)", "dialog.allFiles": "Все файлы (*)", "common.close": "Закрыть",
            "sources.title": "Источники", "sources.subtitle": "Добавьте материал для сравнения", "sources.loaded": "видео добавлено", "sources.dropTitle": "Перетащите видео сюда", "sources.dropHint": "или выберите файлы ниже", "sources.add": "Добавить видео", "sources.folder": "Выбрать папку", "sources.clear": "Очистить", "sources.remove": "Удалить", "sources.empty": "Список пока пуст",
            "search.similarityGroup": "Точность совпадения", "search.similarity": "Порог схожести", "search.candidate": "Порог кандидата", "search.spacingGroup": "Временные зазоры", "search.repeatGap": "Минимальный зазор повторов", "search.sameFileGap": "Зазор в одном видео", "search.crossFileGap": "Зазор между видео", "search.duplicateWindow": "Окно дубликатов", "search.rankingGroup": "Шум и ранжирование", "search.noise": "Коэффициент шума", "search.maxResults": "Максимум уникальных", "search.timeWeight": "Вес времени", "search.quality": "Качество анализа", "search.fast": "Быстро", "search.medium": "Средне", "search.maximum": "Максимум", "search.normalize": "Нормализовать размер", "search.mirror": "Учитывать зеркальные позы", "search.start": "Запустить анализ", "search.running": "Идёт анализ…",
            "stats.files": "Файлы", "stats.frames": "Кадры", "stats.scenes": "Сцены", "stats.pairs": "Пары", "stats.duration": "Длительность", "stats.status": "Состояние", "stats.progress": "Прогресс",
            "center.comparison": "Сравнение", "center.processing": "обрабатываем материал", "center.selected": "выбрана пара", "center.waiting": "ожидание материала", "center.motionField": "поле движения", "center.poseCount": "поз найдено", "center.noMaterial": "материал не выбран", "center.emptyTitle": "Добавьте видео для поиска повторений", "center.emptyHint": "Начните с одного или нескольких файлов", "center.readyTitle": "Движение готово к сравнению", "center.readyHint": "Запустите анализ, чтобы увидеть пары",
            "timeline.title": "ТАЙМЛАЙН", "timeline.play": "Воспроизвести выбранную пару", "timeline.left": "A", "timeline.right": "B", "timeline.markers": "Маркеры пары", "timeline.zoomOut": "Уменьшить масштаб таймлайна", "timeline.zoomIn": "Увеличить масштаб таймлайна", "timeline.fullscreen": "Открыть таймлайн на весь экран",
            "results.title": "Результаты", "results.found": "найдено", "results.emptyHint": "Результаты появятся здесь", "results.emptyBody": "Когда анализ закончится, здесь появятся пары повторяющихся движений.", "results.previous": "Предыдущая пара", "results.next": "Следующая пара", "results.sort": "Сортировка", "results.export": "Экспорт", "results.filters": "Категории движения", "results.all": "Все", "results.forward": "К камере", "results.side": "В сторону", "results.selectPair": "выбрать пару",
            "settings.windowTitle": "Настройки Parallel Finder", "settings.title": "Настройки анализа", "settings.subtitle": "Параметры сохраняются для следующих запусков.", "settings.environment": "Среда анализа", "settings.provider": "Провайдер", "settings.theme": "Тема", "settings.themeValue": "Parallel / dark", "settings.language": "Язык", "settings.languageValue": "Русский", "settings.languageRussian": "Русский", "settings.languageEnglish": "English", "settings.models": "Модели и кэш", "settings.poseModel": "Модель поз", "settings.cache": "Кэш", "settings.scene": "Детектор сцен", "settings.matcher": "Параметры матчера", "settings.matcherHint": "Девять параметров слева управляют поиском всех пар и сохраняются автоматически.", "settings.reset": "Сбросить параметры анализа", "settings.cachePath": "Путь к кэшу", "settings.cacheLimit": "Лимит кэша, ГБ", "settings.modelPath": "Путь к модели", "settings.browse": "Выбрать", "settings.sceneThreshold": "Порог сцены", "settings.saved": "Сохранено автоматически", "settings.reducedMotion": "Уменьшить анимации", "settings.tabAnalysis": "Анализ", "settings.tabAppearance": "Оформление", "settings.tabKeyboard": "Клавиши", "settings.appearanceTitle": "Оформление и кастомизация", "settings.appearanceSubtitle": "Настройте акцент, контекстный цвет и типографику. Изменения применяются сразу.", "settings.palette": "Палитра", "settings.accentAction": "Терракота · действие", "settings.sageContext": "Сейдж · контекст", "settings.changeColor": "Изменить цвет", "settings.editEnabled": "Редактирование включено", "settings.enableEdit": "Включить точечное редактирование", "settings.font": "Шрифт интерфейса", "settings.surfaceOpacity": "Прозрачность поверхностей", "settings.radiusScale": "Радиус карточек", "settings.resetAppearance": "Сбросить оформление", "settings.exportTheme": "Экспорт .pftheme", "settings.importTheme": "Импорт .pftheme", "settings.profileSaved": "Профиль оформления сохраняется автоматически для текущего пользователя.", "settings.profileSaveSuccess": "Профиль сохранён", "settings.profileSaveFailed": "Не удалось сохранить профиль", "settings.profileNotRecognized": "Профиль не распознан", "settings.profileApplied": "Профиль применён", "settings.modelPlaceholder": "models / yolo26m-pose.onnx", "settings.cachePlaceholder": "%LocalAppData%/ParallelFinder/cache", "settings.colorDialog": "Цвет интерфейса", "settings.a11yTitle": "Клавиши и доступность", "settings.a11ySubtitle": "Основные действия доступны без мыши. Фокус подсвечивается терракотовой рамкой.", "settings.keyTab": "переход между контролами", "settings.keyArrows": "списки файлов и результатов", "settings.keyEnter": "выбор элемента или удаление выбранного файла", "settings.keyEscape": "закрыть настройки или fullscreen таймлайн", "settings.a11yHint": "Для уменьшения анимации используйте переключатель во вкладке «Оформление».",
            "export.title": "Подготовить результаты", "export.selected": "пар выбрано для экспорта", "export.format": "Формат", "export.numbering": "Нумерация", "export.asVideo": "Как в видео", "export.bySort": "По сортировке", "export.cutMode": "Нарезка", "export.exact": "Точно", "export.fast": "Быстро", "export.folder": "Папка вывода", "export.prefix": "Префикс файлов", "export.chooseFolder": "Выбрать папку", "export.hint": "EDL, FCPXML и AEP используют FPS исходного материала. Файлы сохраняются в выбранную папку.", "export.prepare": "Экспортировать", "export.done": "Экспорт завершён", "export.failed": "Экспорт не выполнен"
        },
        en: { "app.title": "Parallel Finder", "app.stage": "local motion analysis", "splash.loading": "Preparing the workspace…", "top.workspace": "workspace", "top.analyzing": "Analyzing", "top.ready": "Ready to work", "top.settings": "Open settings", "sources.add": "Add video", "center.emptyTitle": "Add video to find repetitions", "center.emptyHint": "Start with one or more files", "results.title": "Results", "settings.title": "Analysis settings", "export.title": "Prepare results" }
    })

    function t(key) {
        const lang = _dict[language] || _dict.en
        return (key in lang) ? lang[key] : ((_dict.ru && key in _dict.ru) ? _dict.ru[key] : key)
    }
}
